version: '3.7'  # Docker Compose version

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Expose Grafana on port 3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning  # Mount provisioning config
      - grafana-storage:/var/lib/grafana  # Save dashboards/plugins
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana admin password
    depends_on:
      - loki  # Grafana waits for Loki to be ready
    restart: always

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"  # Loki API on 3100
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml  # Loki config
      - loki-storage:/loki
    command: -config.file=/etc/loki/local-config.yml
    environment:
      - LOKI_RETENTION_PERIOD=24h  # Loki retention period
    restart: always

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml  # Your Promtail config
      - ./logs:/var/log/custom  # Folder with your custom logs
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    environment:
      - PROMTAIL_SCRAPE_INTERVAL=10s  # Promtail scrape interval
    restart: always

volumes:
  grafana-storage:  # Volume for Grafana persistence
  loki-storage:
