apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      filters:
        - observed_timestamp_rfc3339
        - instrumentation_scope
        - severity_text
