server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: jenkins-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jenkins-pipeline
          __path__: /var/log/custom/sample-logs.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: severity_text
            scope: instrumentation_scope
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339
