server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: demo-log-job
    static_configs:
      - targets: [localhost]
        labels:
          job: demo-log-job
          __path__: /var/log/custom/sample-logs.json          # Our mounted log file
    pipeline_stages:
      - json:
          expressions:
            observed_timestamp_rfc3339: timestamp
            instrumentation_scope: scope
            severity_text: level
      - labels:
          observed_timestamp_rfc3339:
          instrumentation_scope:
          severity_text:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05Z
